(function() {
  var template = Handlebars.template, templates = Handlebars.templates = Handlebars.templates || {};
templates['billingInfoData'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<div class=\"heading\" style=\"color: white; line-height: 1.25; font-size: 4.5mm; padding-top: 0.5mm;\">"
    + alias4(((helper = (helper = helpers.billingInfo || (depth0 != null ? depth0.billingInfo : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"billingInfo","hash":{},"data":data}) : helper)))
    + "</div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 33mm; border: none;\">"
    + alias4(((helper = (helper = helpers.insurance || (depth0 != null ? depth0.insurance : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"insurance","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n    <div class=\"checkBox\" style=\"border: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 8mm; border: none; text-align: left; padding-left: 1mm\">"
    + alias4(((helper = (helper = helpers.ip || (depth0 != null ? depth0.ip : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"ip","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n    <div class=\"checkBox\" style=\"border: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 13mm; border: none; text-align: left; padding-left: 1mm\">"
    + alias4(((helper = (helper = helpers.op || (depth0 != null ? depth0.op : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"op","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n    <div class=\"checkBox\" style=\"border: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 30mm; border: none; text-align: left; padding-left: 1mm\">"
    + alias4(((helper = (helper = helpers.privatePractice || (depth0 != null ? depth0.privatePractice : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"privatePractice","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n    <div class=\"checkBox\" style=\"border: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 38mm; border: none; text-align: left; padding-left: 1mm\">"
    + alias4(((helper = (helper = helpers.hospitalOwned || (depth0 != null ? depth0.hospitalOwned : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hospitalOwned","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n    <div class=\"checkBox\" style=\"border: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none; text-align: left; padding-left: 1mm\">"
    + alias4(((helper = (helper = helpers.patientInsurance || (depth0 != null ? depth0.patientInsurance : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"patientInsurance","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n    <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none; text-align: left; padding-left: 1mm\">"
    + alias4(((helper = (helper = helpers.uninsured || (depth0 != null ? depth0.uninsured : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"uninsured","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n    <div class=\"checkBox\" style=\"border: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 19.5mm; border: none; text-align: left; padding-left: 1mm;\">"
    + alias4(((helper = (helper = helpers.medicare || (depth0 != null ? depth0.medicare : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"medicare","hash":{},"data":data}) : helper)))
    + "</div>\r\n</div>\r\n<div class=\"whiteBox\" style=\"width: 217mm; border: none; text-align: center\"><span class=\"highlight\">"
    + alias4(((helper = (helper = helpers.demographics || (depth0 != null ? depth0.demographics : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"demographics","hash":{},"data":data}) : helper)))
    + "</span></div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 37mm; border: none; text-align: right; padding-left: 1mm;\">"
    + alias4(((helper = (helper = helpers.primary || (depth0 != null ? depth0.primary : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"primary","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 68mm; border: none;\">\r\n    <div class=\"underLine\" style=\"border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 40mm; text-align: right; border: none; text-align: left; padding-left: 1mm;\">"
    + alias4(((helper = (helper = helpers.secondary || (depth0 != null ? depth0.secondary : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"secondary","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 68mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 65mm; border-bottom: 1px solid \"></div>\r\n  </div>\r\n</div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 15mm; border: none\">"
    + alias4(((helper = (helper = helpers.insuranceID || (depth0 != null ? depth0.insuranceID : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"insuranceID","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 33.75mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 33.75mm; border-bottom: 1px solid \"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; padding-left: 1mm; border: none;\">"
    + alias4(((helper = (helper = helpers.insuranceGroup || (depth0 != null ? depth0.insuranceGroup : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"insuranceGroup","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 33.75mm; padding-left: 1mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 33.75mm;border-bottom: 1px solid \"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 15mm; padding-left: 1mm; border: none\">"
    + alias4(((helper = (helper = helpers.insuranceID || (depth0 != null ? depth0.insuranceID : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"insuranceID","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 35mm; padding-left: 1mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 35mm;border-bottom: 1px solid \"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; padding-left: 1mm; border: none;\">"
    + alias4(((helper = (helper = helpers.insuranceGroup || (depth0 != null ? depth0.insuranceGroup : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"insuranceGroup","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 35mm; padding-left: 1mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 35mm;border-bottom: 1px solid \"></div>\r\n  </div>\r\n</div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 32mm; border: none;\">"
    + alias4(((helper = (helper = helpers.policyHolder || (depth0 != null ? depth0.policyHolder : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"policyHolder","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 35mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 35mm; border-bottom: 1px solid \"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">"
    + alias4(((helper = (helper = helpers.dateOfBirth || (depth0 != null ? depth0.dateOfBirth : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dateOfBirth","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 20mm; border-bottom: 1px solid \"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 32mm; border: none;\">"
    + alias4(((helper = (helper = helpers.policyHolder || (depth0 != null ? depth0.policyHolder : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"policyHolder","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 35mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 35mm; border-bottom: 1px solid \"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">"
    + alias4(((helper = (helper = helpers.dateOfBirth || (depth0 != null ? depth0.dateOfBirth : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dateOfBirth","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 20mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n</div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 15mm; border: none;\">"
    + alias4(((helper = (helper = helpers.address || (depth0 != null ? depth0.address : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"address","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 55mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 55mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 15mm; border: none;\">"
    + alias4(((helper = (helper = helpers.phoneNumber || (depth0 != null ? depth0.phoneNumber : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"phoneNumber","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 20mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 15mm; border: none;\">"
    + alias4(((helper = (helper = helpers.address || (depth0 != null ? depth0.address : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"address","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 55mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 55mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 15mm; border: none;\">"
    + alias4(((helper = (helper = helpers.phoneNumber || (depth0 != null ? depth0.phoneNumber : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"phoneNumber","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 20mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n</div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 10mm; border: none;\">"
    + alias4(((helper = (helper = helpers.city || (depth0 != null ? depth0.city : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"city","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 40mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 40mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 8mm; border: none;\">"
    + alias4(((helper = (helper = helpers.state || (depth0 != null ? depth0.state : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"state","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 15mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 15mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 8mm; border: none;\">"
    + alias4(((helper = (helper = helpers.zipCode || (depth0 != null ? depth0.zipCode : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"zipCode","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 25mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 25mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 10mm; border: none;\">"
    + alias4(((helper = (helper = helpers.city || (depth0 != null ? depth0.city : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"city","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 40mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 40mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 8mm; border: none;\">"
    + alias4(((helper = (helper = helpers.state || (depth0 != null ? depth0.state : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"state","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 15mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 15mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n  <div class=\"whiteBox\" style=\"width: 8mm; border: none;\">"
    + alias4(((helper = (helper = helpers.zipCode || (depth0 != null ? depth0.zipCode : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"zipCode","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"whiteBox\" style=\"width: 25mm; border: none;\">\r\n    <div class=\"underLine\" style=\"width: 25mm; border-bottom: 1px solid\"></div>\r\n  </div>\r\n</div>\r\n";
},"useData":true});
templates['patientInfoData'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 25mm; line-height: 1;\">"
    + alias4(((helper = (helper = helpers.patientName || (depth0 != null ? depth0.patientName : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"patientName","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 65mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 10mm;\">"
    + alias4(((helper = (helper = helpers.firstName || (depth0 != null ? depth0.firstName : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"firstName","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 50mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 6mm;\">"
    + alias4(((helper = (helper = helpers.middleName || (depth0 != null ? depth0.middleName : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"middleName","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 8.5mm;\"></div>\r\n  <div class=\"yellowBox\" style=\"width: 15mm; line-height: 1;\">"
    + alias4(((helper = (helper = helpers.orderingProvider || (depth0 != null ? depth0.orderingProvider : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"orderingProvider","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"yellowBox\" style=\"width: 35mm; border-right: 1px solid ;\"></div>\r\n</div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 20mm;\">"
    + alias4(((helper = (helper = helpers.dateOfBirth || (depth0 != null ? depth0.dateOfBirth : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dateOfBirth","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 19mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 9mm;\">"
    + alias4(((helper = (helper = helpers.sex || (depth0 != null ? depth0.sex : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"sex","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 8mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 9mm;\">"
    + alias4(((helper = (helper = helpers.socialSecurityNumber || (depth0 != null ? depth0.socialSecurityNumber : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"socialSecurityNumber","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 40mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 12mm;\">"
    + alias4(((helper = (helper = helpers.phoneNumber || (depth0 != null ? depth0.phoneNumber : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"phoneNumber","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 40mm;\"></div>\r\n  <div class=\"yellowBox\" style=\"width: 12mm;\">"
    + alias4(((helper = (helper = helpers.chartNumber || (depth0 != null ? depth0.chartNumber : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"chartNumber","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"yellowBox\" style=\"width: 45mm; border-right: 1px solid;\"></div>\r\n</div>\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 28mm;\">"
    + alias4(((helper = (helper = helpers.patientAddress || (depth0 != null ? depth0.patientAddress : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"patientAddress","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 67mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 8mm;\">"
    + alias4(((helper = (helper = helpers.city || (depth0 != null ? depth0.city : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"city","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 52mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 6mm;\">"
    + alias4(((helper = (helper = helpers.state || (depth0 != null ? depth0.state : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"state","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 20.5mm;\"></div>\r\n  <div class=\"whiteBox\" style=\"width: 7mm;\">"
    + alias4(((helper = (helper = helpers.zipCode || (depth0 != null ? depth0.zipCode : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"zipCode","hash":{},"data":data}) : helper)))
    + "</div>\r\n  <div class=\"brownBox\" style=\"width: 26mm; border-right: 1px solid;\"></div>\r\n</div>\r\n";
},"useData":true});
templates['tissueBiopsyData'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "      <div class=\"whiteBox\" style=\"width: 217mm; font-weight: bold; text-align: center; border: none; background: #a95346; color: white; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm; padding-top: 0.5mm;\">"
    + alias4(((helper = (helper = helpers.biopsy || (depth0 != null ? depth0.biopsy : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"biopsy","hash":{},"data":data}) : helper)))
    + "</div>\r\n\r\n\r\n        <div class=\"whiteBox\" style=\"width: 97.5mm; height: 43mm; border: 1px solid; border-right: none\">\r\n\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm; font-weight: bold; text-decoration: underline\">"
    + alias4(((helper = (helper = helpers.specimenSource || (depth0 != null ? depth0.specimenSource : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"specimenSource","hash":{},"data":data}) : helper)))
    + "</div>\r\n          </div>\r\n\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n              <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n            </div>\r\n            <div class=\"whiteBox\" style=\"width: 25mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.cxbx || (depth0 != null ? depth0.cxbx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"cxbx","hash":{},"data":data}) : helper)))
    + "</div>\r\n              <div class=\"whiteBox\" style=\"width: 60mm; border: none;\">\r\n                <div class=\"underLine\" style=\"width: 60mm;border-bottom: 1px solid \"></div>\r\n              </div>\r\n          </div>\r\n\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n              <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n            </div>\r\n            <div class=\"whiteBox\" style=\"width: 25mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.vulvabx || (depth0 != null ? depth0.vulvabx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vulvabx","hash":{},"data":data}) : helper)))
    + "</div>\r\n          </div>\r\n\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n              <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n            </div>\r\n            <div class=\"whiteBox\" style=\"width: 25mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.vagbx || (depth0 != null ? depth0.vagbx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vagbx","hash":{},"data":data}) : helper)))
    + "</div>\r\n          </div>\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n              <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n            </div>\r\n            <div class=\"whiteBox\" style=\"width: 45mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.ecc || (depth0 != null ? depth0.ecc : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"ecc","hash":{},"data":data}) : helper)))
    + "</div>\r\n          </div>\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n              <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n            </div>\r\n            <div class=\"whiteBox\" style=\"width: 45mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.emb || (depth0 != null ? depth0.emb : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"emb","hash":{},"data":data}) : helper)))
    + "</div>\r\n          </div>\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n              <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n            </div>\r\n            <div class=\"whiteBox\" style=\"width: 25mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.leep || (depth0 != null ? depth0.leep : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"leep","hash":{},"data":data}) : helper)))
    + "</div>\r\n          </div>\r\n\r\n          <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n            <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n              <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n            </div>\r\n            <div class=\"whiteBox\" style=\"width: 10mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.other || (depth0 != null ? depth0.other : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"other","hash":{},"data":data}) : helper)))
    + "</div>\r\n              <div class=\"whiteBox\" style=\"width: 80mm; border: none;\">\r\n                <div class=\"underLine\" style=\"width: 80mm;border-bottom: 1px solid \"></div>\r\n              </div>\r\n          </div>\r\n\r\n      </div>\r\n\r\n      <div class=\"whiteBox\" style=\"width: 118.68mm; height: 43mm; border: 1px solid\">\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n            <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n          </div>\r\n          <div class=\"whiteBox\" style=\"width: 75mm; border: none; line-height: 2; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.correlation || (depth0 != null ? depth0.correlation : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"correlation","hash":{},"data":data}) : helper)))
    + "</div>\r\n        </div>\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 25mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2\">"
    + alias4(((helper = (helper = helpers.clinicalHistory || (depth0 != null ? depth0.clinicalHistory : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"clinicalHistory","hash":{},"data":data}) : helper)))
    + "</div>\r\n            <div class=\"whiteBox\" style=\"width: 87mm; border: none;\">\r\n              <div class=\"underLine\" style=\"width: 87mm;border-bottom: 1px solid \"></div>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 110mm; border: none; padding-left: 2mm\">\r\n            <div class=\"underLine\" style=\"width: 110mm;border-bottom: 1px solid \"></div>\r\n          </div>\r\n        </div>\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 45mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.hormoneTherapySpec || (depth0 != null ? depth0.hormoneTherapySpec : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hormoneTherapySpec","hash":{},"data":data}) : helper)))
    + "</div>\r\n            <div class=\"whiteBox\" style=\"width: 65mm; border: none;\">\r\n              <div class=\"underLine\" style=\"width: 65mm;border-bottom: 1px solid \"></div>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 110mm; border: none; padding-left: 2mm\">\r\n            <div class=\"underLine\" style=\"width: 110mm; border-bottom: 1px solid \"></div>\r\n          </div>\r\n        </div>\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.clinDiag || (depth0 != null ? depth0.clinDiag : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"clinDiag","hash":{},"data":data}) : helper)))
    + "</div>\r\n            <div class=\"whiteBox\" style=\"width: 75mm; border: none;\">\r\n              <div class=\"underLine\" style=\"width: 75mm; border-bottom: 1px solid \"></div>\r\n            </div>\r\n        </div>\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 110mm; border: none; padding-left: 2mm\">\r\n            <div class=\"underLine\" style=\"width: 110mm;border-bottom: 1px solid \"></div>\r\n          </div>\r\n        </div>\r\n\r\n        <div class=\"whiteBox\" style=\"width: 118mm; height: 4.5mm; border: none\">\r\n          <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.signature || (depth0 != null ? depth0.signature : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"signature","hash":{},"data":data}) : helper)))
    + "</div>\r\n            <div class=\"whiteBox\" style=\"width: 75mm; border: none;\">\r\n              <div class=\"underLine\" style=\"width: 75mm; border-bottom: 1px solid \"></div>\r\n            </div>\r\n        </div>\r\n";
},"useData":true});
templates['topData'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<!DOCTYPE html>\r\n<html>\r\n  <head>\r\n    <meta charset=\"utf-8\">\r\n    <link rel=\"stylesheet\" href=\"style.css\">\r\n    <title></title>\r\n  </head>\r\n  <body>\r\n    <div class=\"page\">\r\n      <div class=\"whiteBox\" style=\"height: 35mm; width: 217mm; border: none\"></div>\r\n      <div class=\"heading\" style=\"background-color: white; line-height: 1.5; font-size: 5mm; display: inline-block\">"
    + alias4(((helper = (helper = helpers.title || (depth0 != null ? depth0.title : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"title","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"heading\" style=\"color: white; line-height: 1.25; font-size: 4.5mm; padding-top: 0.5mm;\">"
    + alias4(((helper = (helper = helpers.subtitle || (depth0 != null ? depth0.subtitle : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"subtitle","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n  </body>\r\n</html>\r\n";
},"useData":true});
templates['womensHealthData'] = template({"compiler":[7,">= 4.0.0"],"main":function(container,depth0,helpers,partials,data) {
    var helper, alias1=depth0 != null ? depth0 : {}, alias2=helpers.helperMissing, alias3="function", alias4=container.escapeExpression;

  return "<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 102.5mm; height: 56.75mm; border-left: 4mm solid;; border-top: 2mm solid; border-bottom: none;\">\r\n    <div class=\"whiteBox\" style=\"width: 25mm; border-bottom: 1mm solid; border-left: none; padding-left: 15mm; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm\">"
    + alias4(((helper = (helper = helpers.test || (depth0 != null ? depth0.test : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"test","hash":{},"data":data}) : helper)))
    + "</div>\r\n    <div class=\"whiteBox\" style=\"width: 6mm; border-bottom: 1mm solid; border-left: none; padding-left: 10mm; border-bottom: 1mm solid\">\r\n      <div class=\"checkBox\" style=\"width: 3mm; height: 3mm; border: 1px solid\"></div>\r\n    </div>\r\n    <div class=\"whiteBox\" style=\"width: 10mm; border-bottom: 1mm solid; border-left: none; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm\">"
    + alias4(((helper = (helper = helpers.yes || (depth0 != null ? depth0.yes : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"yes","hash":{},"data":data}) : helper)))
    + "</div>\r\n    <div class=\"whiteBox\" style=\"width: 6mm; border-bottom: 1mm solid; border-left: none; padding-left: 10mm;\">\r\n      <div class=\"checkBox\" style=\"width: 3mm; height:3mm; border: 1px solid\"></div>\r\n    </div>\r\n    <div class=\"whiteBox\" style=\"width: 10mm; border-bottom: 1mm solid; border-left: none; padding-right: 10.5mm; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm\">"
    + alias4(((helper = (helper = helpers.no || (depth0 != null ? depth0.no : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"no","hash":{},"data":data}) : helper)))
    + "</div>\r\n    <div class=\"yellowBox\" style=\"width: 102.5mm; border: none; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm;\">"
    + alias4(((helper = (helper = helpers.history || (depth0 != null ? depth0.history : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"history","hash":{},"data":data}) : helper)))
    + "</div>\r\n    <div class=\"yellowBox\" style=\"width: 102.5mm; border-bottom: 1mm solid; border-left: none; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm;\">"
    + alias4(((helper = (helper = helpers.codeRequired || (depth0 != null ? depth0.codeRequired : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"codeRequired","hash":{},"data":data}) : helper)))
    + "</div>\r\n    <div class=\"whiteBox\" style=\"width: 50mm; height: 4mm; border: none; line-height: 1.25; letter-spacing: .1mm; font-size: 3mm; text-decoration: underline; font-weight: bold; text-align: left; padding-left: 1mm;\">"
    + alias4(((helper = (helper = helpers.specimenSource || (depth0 != null ? depth0.specimenSource : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"specimenSource","hash":{},"data":data}) : helper)))
    + "</div>\r\n    <div class=\"whiteBox\" style=\"width: 50mm; height: 4mm; border: none; line-height: 1.25; letter-spacing: .1mm; font-size: 3mm; text-decoration: underline; font-weight: bold; text-align: left; padding-left: 1mm;\">"
    + alias4(((helper = (helper = helpers.specimenType || (depth0 != null ? depth0.specimenType : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"specimenType","hash":{},"data":data}) : helper)))
    + "</div>\r\n\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 45mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.vaginal || (depth0 != null ? depth0.vaginal : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vaginal","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 40mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.thinPrep || (depth0 != null ? depth0.thinPrep : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"thinPrep","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 45mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.ce || (depth0 != null ? depth0.ce : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"ce","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 40mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.urine || (depth0 != null ? depth0.urine : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"urine","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 10mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.other || (depth0 != null ? depth0.other : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"other","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none;\">\r\n        <div class=\"underLine\" style=\"width: 25mm; border-bottom: 1px solid\"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 20mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.blood || (depth0 != null ? depth0.blood : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"blood","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 50mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\"></div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 20mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.swab || (depth0 != null ? depth0.swab : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"swab","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none; padding-left: 2mm; padding-top: 2mm\">\r\n      <div class=\"yellowBox\" style=\"width: 25mm; height: 4mm;border: none; font-size: 3mm; line-height: 2; font-weight: bold; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.collectionDate || (depth0 != null ? depth0.collectionDate : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"collectionDate","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">\r\n        <div class=\"underLine\" style=\"width: 20mm; border-bottom: 1px solid; background-color: #fff19c\"></div>\r\n      </div>\r\n      <div class=\"yellowBox\" style=\"width: 23mm.5; height: 4mm;border: none; font-size: 3mm; padding-left: 2mm; line-height: 2; font-weight: bold; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.collectionTime || (depth0 != null ? depth0.collectionTime : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"collectionTime","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 20mm; border: none;\">\r\n        <div class=\"underLine\" style=\"width: 20mm; border-bottom: 1px solid; background-color: #fff19c\"></div>\r\n      </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none; padding-left: 2mm;\">\r\n\r\n      <div class=\"whiteBox\" style=\"width: 45.75mm; border: none; padding-left: 2mm; padding-top: 2mm\">\r\n        <div class=\"whiteBox\" style=\"width: 6mm; border: none; padding-top: .5mm\">\r\n          <div class=\"checkBox\" style=\"border: 1px solid; height: 3mm; width: 3mm \"></div>\r\n        </div>\r\n        <div class=\"whiteBox\" style=\"width: 25mm; height: 4mm;border: none; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm; font-weight: bold; letter-spacing: .1mm; text-align: left\">"
    + alias4(((helper = (helper = helpers.screening || (depth0 != null ? depth0.screening : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"screening","hash":{},"data":data}) : helper)))
    + "</div>\r\n      </div>\r\n\r\n      <div class=\"whiteBox\" style=\"width: 45.75mm; border: none; padding-left: 2mm; padding-top: 2mm\">\r\n        <div class=\"whiteBox\" style=\"width: 6mm; border: none; padding-top: .5mm\">\r\n          <div class=\"checkBox\" style=\"border: 1px solid; height: 3mm; width: 3mm \"></div>\r\n        </div>\r\n        <div class=\"whiteBox\" style=\"width: 25mm; height: 4mm;border: none; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm; font-weight: bold; letter-spacing: .1mm; text-align: left\">"
    + alias4(((helper = (helper = helpers.diagnostic || (depth0 != null ? depth0.diagnostic : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"diagnostic","hash":{},"data":data}) : helper)))
    + "</div>\r\n      </div>\r\n    </div>\r\n  </div>\r\n\r\n\r\n\r\n\r\n\r\n  <div class=\"whiteBox\" style=\"width: 102.5mm; height: 55mm; border-right: 4mm solid; border-left: 4mm solid; border-top: 2mm solid; border-bottom: 2mm solid;\">\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none;\">\r\n      <div class=\"yellowBox\" style=\"width: 102.5mm; border: none; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; font-size: 4.5mm;\">"
    + alias4(((helper = (helper = helpers.additionalTesting || (depth0 != null ? depth0.additionalTesting : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"additionalTesting","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none;\">\r\n      <div class=\"yellowBox\" style=\"width: 102.5mm; height: 4mm;border: none; font-weight: bold; font-size: 2.5mm; line-height: 1.5; letter-spacing: .1mm; border-bottom: 1mm solid;\">"
    + alias4(((helper = (helper = helpers.cannotProcess || (depth0 != null ? depth0.cannotProcess : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"cannotProcess","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none;\">\r\n      <div class=\"whiteBox\" style=\"width: 20mm; height: 5mm;border: none; font-weight: bold; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: center; padding-left: 1mm; text-decoration: underline;\">"
    + alias4(((helper = (helper = helpers.hpvTesting || (depth0 != null ? depth0.hpvTesting : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hpvTesting","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 75mm; height: 5mm;border: none; font-weight: bold; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.screeningGenotyping || (depth0 != null ? depth0.screeningGenotyping : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"screeningGenotyping","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none;\">\r\n      <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n        <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n          <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n        </div>\r\n        <div class=\"whiteBox\" style=\"width: 46mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.routineHpv || (depth0 != null ? depth0.routineHpv : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"routineHpv","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 46mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\"></div>\r\n      </div>\r\n    </div>\r\n\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 43mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left; padding: none\">"
    + alias4(((helper = (helper = helpers.ascusOnly || (depth0 != null ? depth0.ascusOnly : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"ascusOnly","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"underLine\" style=\"width: 30mm;border-bottom: 1px solid \"></div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 43mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left; padding: none\">"
    + alias4(((helper = (helper = helpers.ascusAbove || (depth0 != null ? depth0.ascusAbove : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"ascusAbove","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"underLine\" style=\"width: 30mm;border-bottom: 1px solid \"></div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 43mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left; padding: none\">"
    + alias4(((helper = (helper = helpers.hpvONLY || (depth0 != null ? depth0.hpvONLY : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hpvONLY","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"underLine\" style=\"width: 30mm;border-bottom: 1px solid \"></div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 6mm; border: none; padding-top: 1mm\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 43mm; height: 5mm;border: none; font-size: 3mm; line-height: 1; letter-spacing: .1mm; text-align: left; padding: none\">"
    + alias4(((helper = (helper = helpers.reflexGenotyping || (depth0 != null ? depth0.reflexGenotyping : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"reflexGenotyping","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"underLine\" style=\"width: 30mm;border-bottom: 1px solid \"></div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none;\">\r\n      <div class=\"whiteBox\" style=\"width: 43mm; height: 5mm;border: none; padding-left: 2mm; font-weight: bold; text-decoration: underline; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left; padding: none\">"
    + alias4(((helper = (helper = helpers.additionalTesting || (depth0 != null ? depth0.additionalTesting : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"additionalTesting","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none; padding-top: 1mm\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 43mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left; padding: none\">"
    + alias4(((helper = (helper = helpers.ngct || (depth0 != null ? depth0.ngct : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"ngct","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"underLine\" style=\"width: 30mm;border-bottom: 1px solid \"></div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none;\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 43mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left; padding: none\">"
    + alias4(((helper = (helper = helpers.trich || (depth0 != null ? depth0.trich : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"trich","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; height: 5mm;border: none; font-size: 3mm; line-height: 2; letter-spacing: .1mm; text-align: left;\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"underLine\" style=\"width: 30mm;border-bottom: 1px solid \"></div>\r\n    </div>\r\n\r\n  </div>\r\n</div>\r\n\r\n\r\n\r\n\r\n<div class=\"row\">\r\n  <div class=\"whiteBox\" style=\"width: 104.5mm; height: 55mm; border-left: 4mm solid; border-bottom: 5mm solid; border-bottom: none;\">\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none; padding-top: 2mm\">\r\n      <div class=\"whiteBox\" style=\"width: 12mm; border: none; font-weight: bold; line-height: 1.5; letter-spacing: .1mm; font-size: 3mm; text-align: right;\">"
    + alias4(((helper = (helper = helpers.lmp || (depth0 != null ? depth0.lmp : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"lmp","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 25mm; padding-left: 1mm; border: none;\">\r\n        <div class=\"underLine\" style=\"width: 25mm;border-bottom: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 15mm; border: none; font-weight: bold; line-height: 1.5; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.icd || (depth0 != null ? depth0.icd : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"icd","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 40mm; padding-left: 1mm; border: none;\">\r\n        <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n      </div>\r\n    </div>\r\n\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 51mm; height: 4mm; border: none; font-weight: bold; font-size: 2.5mm; line-height: 1.5; letter-spacing: .1mm; text-align: right\"></div>\r\n      <div class=\"yellowBox\" style=\"width: 46mm; height: 4mm; border: none; font-weight: bold; font-size: 2.5mm; line-height: 1.5; letter-spacing: .1mm;\">"
    + alias4(((helper = (helper = helpers.cannotProcess || (depth0 != null ? depth0.cannotProcess : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"cannotProcess","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 102.5mm; border: none; font-weight: bold; line-height: 1.25; letter-spacing: .1mm; padding-left: 2mm; font-size: 3mm; text-align: left; text-decoration: underline;\">"
    + alias4(((helper = (helper = helpers.clinicalHistory || (depth0 != null ? depth0.clinicalHistory : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"clinicalHistory","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.75mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.abnormalBleeding || (depth0 != null ? depth0.abnormalBleeding : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"abnormalBleeding","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.75mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.prenatal || (depth0 != null ? depth0.prenatal : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"prenatal","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.75mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.postPartum || (depth0 != null ? depth0.postPartum : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"postPartum","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none;; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.75mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.postMenopausal || (depth0 != null ? depth0.postMenopausal : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"postMenopausal","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.75mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.highRisk || (depth0 != null ? depth0.highRisk : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"highRisk","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.75mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.bcp || (depth0 != null ? depth0.bcp : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"bcp","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; height: 4.75mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.depo || (depth0 != null ? depth0.depo : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"depo","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n  </div>\r\n\r\n\r\n\r\n  <div class=\"whiteBox\" style=\"width: 104.5mm; height: 55mm; border-right: 4mm solid; border-left: none; border-bottom: none;\">\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none; padding-left: 2mm;\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 33mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.hysterectomy || (depth0 != null ? depth0.hysterectomy : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hysterectomy","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 25mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.cervixPresent || (depth0 != null ? depth0.cervixPresent : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"cervixPresent","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 10mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.yes || (depth0 != null ? depth0.yes : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"yes","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 4mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 10mm; border: none;; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.no || (depth0 != null ? depth0.no : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"no","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.hormoneTherapy || (depth0 != null ? depth0.hormoneTherapy : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"hormoneTherapy","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.cervicitis || (depth0 != null ? depth0.cervicitis : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"cervicitis","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.vaginitis || (depth0 != null ? depth0.vaginitis : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"vaginitis","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none;\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.other || (depth0 != null ? depth0.other : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"other","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 25mm; padding-left: 2mm; border: none;\">\r\n        <div class=\"underLine\" style=\"width: 25mm;border-bottom: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm\">"
    + alias4(((helper = (helper = helpers.dx || (depth0 != null ? depth0.dx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"dx","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 1mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none; height: 4.75mm;\">\r\n      <div class=\"whiteBox\" style=\"width: 45mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-weight: bold; text-decoration: underline; font-size: 3mm; text-align: left; padding-left: 3mm\">"
    + alias4(((helper = (helper = helpers.papHistory || (depth0 != null ? depth0.papHistory : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"papHistory","hash":{},"data":data}) : helper)))
    + "</div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.pnp || (depth0 != null ? depth0.pnp : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"pnp","hash":{},"data":data}) : helper)))
    + "</div>\r\n\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.date || (depth0 != null ? depth0.date : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"date","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 2mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.pab || (depth0 != null ? depth0.pab : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"pab","hash":{},"data":data}) : helper)))
    + "</div>\r\n\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.date || (depth0 != null ? depth0.date : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"date","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 2mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n\r\n    <div class=\"whiteBox\" style=\"width: 97.5mm; border: none\">\r\n      <div class=\"whiteBox\" style=\"width: 5mm; border: none; padding-left: 2mm\">\r\n        <div class=\"checkBox\" style=\"border: 1px solid \"></div>\r\n      </div>\r\n      <div class=\"whiteBox\" style=\"width: 35mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; text-align: left; padding-left: 2mm\">"
    + alias4(((helper = (helper = helpers.pbx || (depth0 != null ? depth0.pbx : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"pbx","hash":{},"data":data}) : helper)))
    + "</div>\r\n      <div class=\"whiteBox\" style=\"width: 6mm; border: none; line-height: 1.75; letter-spacing: .1mm; font-size: 3mm; padding-left: 2mm;\">"
    + alias4(((helper = (helper = helpers.date || (depth0 != null ? depth0.date : depth0)) != null ? helper : alias2),(typeof helper === alias3 ? helper.call(alias1,{"name":"date","hash":{},"data":data}) : helper)))
    + "</div>\r\n        <div class=\"whiteBox\" style=\"width: 30mm; padding-left: 2mm; border: none;\">\r\n          <div class=\"underLine\" style=\"width: 42mm;border-bottom: 1px solid \"></div>\r\n        </div>\r\n    </div>\r\n</div>\r\n";
},"useData":true});
})();